### ISSUE TITLE
[FEATURE]: Check YAML files for formatting and errors

### ISSUE THREAD

**Issue by szepeviktor** [meetrevision/playbook#156]
### Description

Would you introduce yamllint?
`.yamllint.yml`
```yaml
extends: "default"

rules:
    document-start:
        present: true
    braces:
        forbid: false
    brackets:
        forbid: true
    empty-values:
        forbid-in-block-mappings: true
        forbid-in-flow-mappings: true
    indentation:
        spaces: 2
        indent-sequences: true
    line-length:
        level: "error"
        max: 200
    comments:
        require-starting-space: false
```

### Benefit

No more inconsistent YAML files,
prevent typos.

### Implementation (Optional)

https://pypi.org/project/yamllint/

### Have you searched for similar feature requests?

- [x] I have searched for similar feature requests and found none.
